### ISSUE TITLE
I want to be able to designate an arbitrary value for the request key

### ISSUE THREAD

**Issue by putan** [putan/stubon#15]
e.g.

If the value is '*' in the string, check only the existence of the key and make it a match.
```
'/aaa/get/{id}':
    -
        request:
            method: 'GET'
            params:
                id: '*'   <- match any id, but if there is no "id", it will be mismatch.
        response:
            status: 200
            body:
                result: 'OK! aaa!'
```
